# This is an example mods.toml file.
# Any fields that aren't annotated with #optional are *required*!
modLoader = "javafml"
loaderVersion = "*"
license = "Lesser GPL License V3" # Want to make your mod open source? Check out https://choosealicense.com/!

# This is a URL to e.g. your GitHub or CurseForge issues page.
# It will appear in any crash reports this mod is directly involved in.
# issueTrackerURL="https://github.com/invalid/pleasechangeme/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader

[[mods]]
modId = "iris"
# The version number of the mod - unlike in the Forge MDK,
# we'll use the processResources task to replace this for us
version = "${version}"
displayName = "Iris"
# This URL will be queried by the Forge update checker in order to find the latest version of your mod.
# If an update is found, you'll see a little blinking "emerald" symbol on your Mods button!
# updateJSONURL="https://changeme.dev/updates.json" #optional
# This is your mod's "homepage" and will be displayed on the mod's information screen in the Mods panel.
displayURL="https://irisshaders.dev/" #optional
# This will be displayed as your mod's logo in the Mods panel.
logoFile="iris-logo.png" #optional
# Some more fluff displayed in the Mods panel. Feel free to issue your special thanks here!
# credits="Thanks to Mojang for making this great game" #optional
# Some more fluff displayed in the Mods panel. Plug your stuff here!
authors="coderbot, IMS212"
# A multi-line description for your mod. This has no minimum length, but it *is* required!
description = '''
A modern shaders mod for Minecraft intended to be compatible with existing OptiFine shader packs.
'''

[mods."sodium:options"]
"mixin.features.render.world.sky"=false
"mixin.features.render.entity"=false
"mixin.features.render.gui.font"=false

[[mixins]]
config = "mixins.iris.json"

[[mixins]]
config = "mixins.iris.neoforge.json"

[[mixins]]
config = "mixins.iris.fantastic.json"

[[mixins]]
config = "mixins.iris.fixes.maxfpscrash.json"

[[mixins]]
config = "mixins.iris.vertexformat.json"

[[mixins]]
config = "mixins.iris.compat.sodium.json"

[[mixins]]
config = "iris-batched-entity-rendering.mixins.json"
