#Qodana
#
name: "Qodana"

on:
  push:
    branches: [ trunk ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ trunk ]
  schedule:
    - cron: '31 3 * * 1'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/work/_temp/_github_home/cache
          key: ${{ runner.os }}-qodana-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-qodana-${{ github.ref }}
            ${{ runner.os }}-qodana-
      - uses: docker://jetbrains/qodana-<linter>
        with:
          args: --cache-dir=/github/home/cache --results-dir=/github/workspace/qodana --save-report --report-dir=/github/workspace/qodana/report
      - uses: actions/upload-artifact@v2
        with:
          path: qodana
